// Prose checks for workflow setup notes. See CONTRIBUTING.md for writing rules.
export const BANNED = [
  { label: 'delve', re: /\bdelve\b/gi },
  { label: 'tapestry', re: /\btapestry\b/gi },
  { label: 'realm', re: /\brealm\b/gi },
  { label: 'embark', re: /\bembark\b/gi },
  { label: 'landscape (figurative)', re: /\blandscape\b/gi },
  { label: 'navigate (figurative)', re: /\bnavigate\b/gi },
  { label: 'leverage (verb)', re: /\bleverag(?:e|es|ed|ing)\b/gi },
  { label: 'unlock', re: /\bunlock\b/gi },
  { label: 'elevate', re: /\belevate\b/gi },
  { label: 'empower', re: /\bempower\b/gi },
  { label: 'streamline', re: /\bstreamline\b/gi },
  { label: 'supercharge', re: /\bsupercharge\b/gi },
  { label: 'revolutionize', re: /\brevolutioni[sz]e\b/gi },
  { label: 'unleash', re: /\bunleash\b/gi },
  { label: 'seamless', re: /\bseamless(?:ly)?\b/gi },
  { label: 'cutting-edge', re: /\bcutting[- ]edge\b/gi },
  { label: 'next-gen', re: /\bnext[- ]gen\b/gi },
  { label: 'game-changer', re: /\bgame[- ]changer\b/gi },
  { label: 'harness', re: /\bharness\b/gi },
  { label: 'robust', re: /\brobust\b/gi },
  { label: 'pivotal', re: /\bpivotal\b/gi },
  { label: 'crucial', re: /\bcrucial\b/gi },
  { label: 'paramount', re: /\bparamount\b/gi },
  { label: 'furthermore', re: /\bfurthermore\b/gi },
  { label: 'moreover', re: /\bmoreover\b/gi },
  { label: 'in conclusion', re: /\bin conclusion\b/gi },
  { label: 'in today’s', re: /\bin today['’]s\b/gi },
  { label: 'fast-paced', re: /\bfast[- ]paced\b/gi },
  { label: 'ever-evolving', re: /\bever[- ]evolving\b/gi },
  { label: 'at the end of the day', re: /\bat the end of the day\b/gi },
  { label: 'here’s the thing', re: /\bhere['’]s the thing\b/gi },
  { label: 'let’s dive in', re: /\blet['’]s dive in\b/gi },
  { label: 'the best part', re: /\bthe best part\b/gi },
  { label: 'peace of mind', re: /\bpeace of mind\b/gi },
  { label: 'effortless', re: /\beffortless(?:ly)?\b/gi },
  { label: '10x', re: /\b10x\b/gi },
  { label: 'magic', re: /\bmagic(?:al)?\b/gi },
  { label: 'AI-powered filler', re: /\bAI[- ]powered\b/gi },
  { label: 'not only … but also', re: /\bnot only\b[\s\S]{0,160}?\bbut also\b/gi },
  { label: 'whether you’re a … or a …', re: /\bwhether you['’]re a\b[\s\S]{0,160}?\bor a\b/gi },
  { label: 'release status language', re: /\b(pilot|beta|alpha|design partner|coming soon|waitlist|phase \d|qualif(?:y|ied|ication))\b/gi },
  { label: 'zero access', re: /\bzero access\b/gi },
  { label: 'military-grade', re: /\bmilitary[- ]grade\b/gi },
  { label: '100% secure', re: /\b100% secure\b/gi },
  { label: 'roadmap dates/promises', re: /\bcoming soon\b/gi },
  { label: 'app URLs', re: /\b(?:https?:\/\/)?app\.operatornest\.com\b/gi },
  { label: 'exclamation mark', re: /!/g },
  { label: 'em dash', re: /—/g },
  { label: 'emoji', re: /\p{Extended_Pictographic}/gu },
  { label: 'heading “Why … matters”', re: /^#{1,6}\s+Why\b[^\n]*\bmatters?\b/gim },
  { label: 'heading “The power of”', re: /^#{1,6}\s+The power of\b[^\n]*/gim },
];

export const RATIONED = [
  { label: 'actually', re: /\bactually\b/gi },
  { label: 'genuinely', re: /\bgenuinely\b/gi },
  { label: 'simply', re: /\bsimply\b/gi },
  { label: 'just', re: /\bjust\b/gi },
  { label: 'really', re: /\breally\b/gi },
  { label: 'quietly', re: /\bquietly\b/gi },
  { label: 'truly', re: /\btruly\b/gi },
  { label: 'the real (problem/question/cost)', re: /\bthe real (?:problem|question|cost)\b/gi },
  { label: 'matters / what matters', re: /\b(?:what )?matters\b/gi },
  { label: 'comes down to', re: /\bcomes down to\b/gi },
  { label: 'not just / not only / not merely', re: /\bnot (?:just|only|merely)\b/gi },
  { label: 'it’s worth noting / worth naming', re: /\b(?:it['’]s )?worth (?:noting|naming|saying|treating|being)\b/gi },
  { label: 'in practice', re: /\bin practice\b/gi },
];

export function matches(rule, text) {
  return [...text.matchAll(new RegExp(rule.re.source, rule.re.flags))];
}
